### elasticsearch|http://localhost:9200|node_storage|=Foo
GET http://localhost:8089/node/encoding/es_test_schema_2 HTTP/1.1
Authorization: Basic admin admin

### elasticsearch|http://localhost:9200|node_storage|=Foo
GET http://localhost:8089/node/encoding HTTP/1.1
Authorization: Basic admin admin
Content-Type: application/json

{
  "smt": "es_test_schema_2"
}

### mysql|host=localhost;user=dicta;password=dicta;database=storage_node|test_schema|=Foo
GET http://localhost:8089/node/encoding/mysql_test_schema_2 HTTP/1.1
Authorization: Basic admin admin
