### drew@drewletcher.net
POST http://localhost:8089/node/retrieve/elasticsearch%7Chttp%3A%2F%2Flocalhost%3A9200%7Ctest_schema%7C* HTTP/1.1
Authorization: Basic user user
Content-Type: application/json

{
  "pattern": {
    "match": {
      "Bar": "row",
      "Baz": { "gte": 100, "lte": 500 }
    },
    "consolidate": {
      "baz_sum": { "sum": "Baz" },
      "dt_min": { "min": "Dt Test" },
      "dt_max": { "max": "Dt Test" }
    }
  }
}
