### transfer test
GET http://localhost:8089/node/transfer/test HTTP/1.1
Authorization: Basic admin admin

### transfer
POST http://localhost:8089/node/transfer HTTP/1.1
Authorization: Basic user user
Content-Type: application/json

{
  "source": {
    "smt": "mysql_foo_schema_pk",
    "options": {}
  },
  "destination": {
    "smt": "es_foo_transfer_2",
    "options": {}
  }
}
