### drew@drewletcher.net
POST http://localhost:8089/node/retrieve/elastic||equipment_repair_history| HTTP/1.1
Authorization: Basic ZHJld0BkcmV3bGV0Y2hlci5uZXQ6cGl6emEx
Content-Type: application/json

{
  "pattern": {
    "match": {
      "dealer": "City ForkLift",
      "invoice_date": { "gte": "2016-01-01", "lte": "2016-12-31" }
    },
    "consolidate": {
      "repair_code": {
        "invoice_price_sum": { "sum": "invoice_price" }
      }
    },
    "cues": {
      "order": { "invoice_price_sum": "desc" },
      "count": 7
    }
  }
}
