### elasticsearch|http://localhost:9200|test_schema|uid
DELETE http://localhost:8089/node/dull/elasticsearch%7Chttp%3A%2F%2Flocalhost%3A9200%7Ctest_schema%7Cfirst HTTP/1.1
Authorization: Basic user user

### elasticsearch|http://localhost:9200|test_schema|!Foo
DELETE http://localhost:8089/node/dull/elasticsearch%7Chttp%3A%2F%2Flocalhost%3A9200%7Ctest_schema%7C!Foo HTTP/1.1
Authorization: Basic user user
Content-Type: application/json

{
  "keys": {
    "key": "first"
  }
}

### elasticsearch|http://localhost:9200|test_schema|=Foo
DELETE http://localhost:8089/node/dull HTTP/1.1
Authorization: Basic user user
Content-Type: application/json

{
  "smt": {
    "model": "elasticsearch",
    "locus": "http://localhost:9200",
    "schema": "test_schema",
    "key": "=Foo"
  },
  "keys": {
    "Foo": "first"
  }
}


### mysql|host=localhost;user=dicta;password=dicta;database=storage_node|test_schema|=Foo
DELETE http://localhost:8089/node/dull/mysql%7Chost%3Dlocalhost%3Buser%3Ddicta%3Bpassword%3Ddicta%3Bdatabase%3Dstorage_node%7Ctest_schema%7C%3DFoo HTTP/1.1
Authorization: Basic user user
Content-Type: application/json

{
  "keys": {
    "Foo": "eleventy"
  }
}
