### elasticsearch|http://localhost:9200|test_schema|*
POST http://localhost:8089/node/retrieve/es_test_schema_0 HTTP/1.1
Authorization: Basic user user
Content-Type: application/json

{
  "pattern": {
    "cues": {
      "order": {"Foo": "asc"},
      "count": 100
    }
  }
}

### elasticsearch|http://localhost:9200|test_schema|*
POST http://localhost:8089/node/retrieve HTTP/1.1
Authorization: Basic user user
Content-Type: application/json

{
  "smt": "es_test_schema_0",
  "pattern": {
    "match": {
      "Foo": "first"
    }
  }
}

### elasticsearch|http://localhost:9200|test_schema|=Foo
POST http://localhost:8089/node/retrieve/es_test_schema_2 HTTP/1.1
Authorization: Basic user user
Content-Type: application/json

{
  "pattern": {
    "match": {
      "Bar": "row",
      "Baz": { "gte": 100, "lte": 500 }
    },
    "cues": {
      "count": 3,
      "order": {"Foo": "asc"}
    }
  }
}


### mysql|host=localhost;user=dicta;password=dicta;database=storage_node|test_schema|=Foo
POST http://localhost:8089/node/retrieve/mysql_test_schema_2 HTTP/1.1
Authorization: Basic user user
Content-Type: application/json

{
}

### mysql|host=localhost;user=dicta;password=dicta;database=storage_node|test_schema|=Foo
POST http://localhost:8089/node/retrieve/mysql_test_schema_2 HTTP/1.1
Authorization: Basic user user
Content-Type: application/json

{
  "match": {
    "Foo": "first"
  }
}

### mysql|host=localhost;user=dicta;password=dicta;database=storage_node|test_schema|=Foo
POST http://localhost:8089/node/retrieve/mysql_test_schema_2 HTTP/1.1
Authorization: Basic user user
Content-Type: application/json

{
  "pattern": {
    "match": {
      "Bar": "row",
      "Baz": { "gte": 100, "lte": 500 }
    },
    "cues": {
      "count": 3,
      "order": {"Dt Test": "desc"}
    }
  }
}
