### transfer with transforms
POST http://localhost:8089/node/transfer HTTP/1.1
Authorization: Basic user user
Content-Type: application/json

{
  "source": {
    "smt": "mysql_foo_schema_pk",
    "options": {}
  },
  "destination": {
    "smt": "es_foo_transfer_3",
    "options": {}
  },
  "transforms": {
    "filter": {
      "match": {
        "Bar": {
          "op": "eq",
          "value": "row"
        }
      },
      "drop": {
        "Baz": {
          "op": "eq",
          "value": 5678
        }
      }
    },
    "fields": {
      "inject": {
        "Fie": "where's fum?"
      },
      "mapping": {
        "Foo": "Foo",
        "Bar": "Bar",
        "Baz": "Bazzy"
      }
    }
  }
}

### transfer with transforms
POST http://localhost:8089/node/transfer HTTP/1.1
Authorization: Basic user user
Content-Type: application/json

{
  "source": {
    "smt": "es_foo_transfer_3",
    "options": {}
  },
  "destination": {
    "smt": "mysql_foo_transfer",
    "options": {}
  },
  "transforms": {
    "filter": {
      "match": {
        "Bar": {
          "op": "eq",
          "value": "row"
        }
      },
      "drop": {
        "Baz": {
          "op": "eq",
          "value": 5678
        }
      }
    },
    "fields": {
      "inject": {
        "Fie": "where's fum?"
      },
      "mapping": {
        "Foo": "Foo",
        "Bar": "Bar",
        "Baz": "Bazzy"
      }
    }
  }
}
