### elasticsearch|http://localhost:9200|foo_schema|uid
DELETE http://localhost:8089/node/dull/es_test_schema_u HTTP/1.1
Authorization: Basic user user

### elasticsearch|http://localhost:9200|foo_schema|!Foo
DELETE http://localhost:8089/node/dull/es_test_schema_1 HTTP/1.1
Authorization: Basic user user
Content-Type: application/json

{
  "match": {
    "key": "first"
  }
}

### elasticsearch|http://localhost:9200|foo_schema|=Foo
DELETE http://localhost:8089/node/dull HTTP/1.1
Authorization: Basic user user
Content-Type: application/json

{
  "smt": "es_test_schema_2",
  "match": {
    "Foo": "first"
  }
}


### mysql|host=localhost;user=dicta;password=dicta;database=storage_node|foo_schema|=Foo
DELETE http://localhost:8089/node/dull/mysql_test_schema_2 HTTP/1.1
Authorization: Basic user user
Content-Type: application/json

{
  "match": {
    "Foo": "eleventy"
  }
}
