### Note, admin user is built-in

### dullboy
POST http://localhost:8089/node/account HTTP/1.1
Authorization: Basic dullboy dullboy
Content-Type: application/json;charset=utf-8

{
  "account": {
    "userid": "dullboy",
    "password": "dullboy"
  }
}

### guest - created by admin with Public role only
POST http://localhost:8089/node/register HTTP/1.1
Authorization: Basic admin admin
Content-Type: application/json;charset=utf-8

{
  "account": {
    "userid": "guest",
    "password": "guest",
    "roles": ["Public"]
  }
}

### user, cannot set roles, defaults to ["Public","User"]
POST http://localhost:8089/node/register HTTP/1.1
Authorization: Basic user user
Content-Type: application/json;charset=utf-8

{
  "account": {
    "userid": "user",
    "password": "user",
    "roles": ["Public", "User", "Admin"]
  }
}
