
### dullboy
DELETE http://dev.dictadata.org:8089/node/accounts HTTP/1.1
Authorization: Basic dullboy dullboy

### dullboy by admin
DELETE http://dev.dictadata.org:8089/node/accounts/dullboy HTTP/1.1
Authorization: Basic admin admin

### guest, by unregistered user
DELETE http://dev.dictadata.org:8089/node/accounts HTTP/1.1
Authorization: Basic aladdin opensesame
Content-Type: application/json; charset=utf-8

{
  "account": {
    "userid": "guest"
  }
}

### guest, does not have User rights
DELETE http://dev.dictadata.org:8089/node/accounts HTTP/1.1
Authorization: Basic guest guest
Content-Type: application/json; charset=utf-8

{
  "account": {
    "userid": "guest"
  }
}

### guest, by admin
DELETE http://dev.dictadata.org:8089/node/accounts/guest HTTP/1.1
Authorization: Basic admin admin

### user
DELETE http://dev.dictadata.org:8089/node/accounts HTTP/1.1
Authorization: Basic user user
Content-Type: application/json; charset=utf-8

{
  "account": {
    "userid": "user"
  }
}
