### dullboy, querystring
GET http://dev.dictadata.org:8089/node/accounts HTTP/1.1
Authorization: Basic dullboy dullboy

### dullboy, querystring
GET http://dev.dictadata.org:8089/node/accounts/dullboy HTTP/1.1
Authorization: Basic admin admin

### dicta
GET http://dev.dictadata.org:8089/node/accounts/dicta HTTP/1.1
Authorization: Basic admin admin

### user
GET http://dev.dictadata.org:8089/node/accounts/user HTTP/1.1
Authorization: Basic admin admin

### drewlab
GET http://dev.dictadata.org:8089/node/accounts/drewlab HTTP/1.1
Authorization: Basic admin admin

### admin
GET http://dev.dictadata.org:8089/node/accounts/drewlab HTTP/1.1
Authorization: Basic admin admin

### admin
GET http://dev.dictadata.org:8089/node/accounts HTTP/1.1
Authorization: Basic admin admin
