### not found
GET http://dev.dictadata.net:8089/node/codex/foo_schema
Authorization: Basic user user

### not found
GET http://dev.dictadata.net:8089/node/codex/:foo_schema
Authorization: Basic user user

### OK
GET http://dev.dictadata.net:8089/node/codex/foo:foo_schema
Authorization: Basic user user

###
POST http://dev.dictadata.net:8089/node/codex
Authorization: Basic user user
Content-Type: application/json; charset=utf-8

{
  "pattern": {
    "match": {
      "name": {
        "wc": "foo_schema*"
      }
    }
  }
}

###
POST http://dev.dictadata.net:8089/node/codex
Authorization: Basic user user
Content-Type: application/json; charset=utf-8

{
  "pattern": {
    "match": {
      "name": {
        "eq": "tigerline"
      }
    }
  }
}

###
DELETE http://dev.dictadata.net:8089/node/codex/foo:foo_schema_XYZ
Authorization: Basic user user

###
PUT http://dev.dictadata.net:8089/node/codex
Authorization: Basic user user
Content-Type: application/json; charset=utf-8

{
  "domain": "foo",
  "name": "foo_schema_XYZ",
  "type": "engram",
  "title": "foo_schema encoding",
  "description": "test input for foo_schema_XYZ encoding",
  "source": "file:./data/input/foo_schema_XYZ.encoding.json",
  "tags": [
    "foo"
  ],
  "smt": {
    "model": "*",
    "locus": "*",
    "schema": "foo_schema",
    "key": "*"
  },
  "fields": [
    {
      "name": "Foo",
      "type": "keyword",
      "size": 64,
      "default": null,
      "nullable": false,
      "key": 1,
      "label": "Foo"
    },
    {
      "name": "Bar",
      "type": "text",
      "size": 256,
      "default": null,
      "nullable": true,
      "label": "Bar"
    },
    {
      "name": "Baz",
      "type": "integer",
      "size": 0,
      "default": null,
      "nullable": true,
      "label": "Baz"
    },
    {
      "name": "Fobe",
      "type": "number",
      "size": 0,
      "default": null,
      "nullable": true,
      "label": "Fobe"
    },
    {
      "name": "Dt Test",
      "type": "date",
      "size": 0,
      "default": null,
      "nullable": true,
      "label": "Dt Test"
    },
    {
      "name": "enabled",
      "type": "boolean",
      "size": 0,
      "default": null,
      "nullable": true,
      "label": "enabled"
    }
  ]
}
