### no user: Unauthorized
GET http://dev.dictadata.org:8089/test/echo HTTP/1.1

### invalid Authorization: defaults to Public role
GET http://dev.dictadata.org:8089/test/echo HTTP/1.1
Authorization: Basic Aladdin opensesame

### Public guest:guest
GET http://dev.dictadata.org:8089/test/echo HTTP/1.1
Authorization: Basic guest guest

### User admin:admin
GET http://dev.dictadata.org:8089/test/echo?a=1&b=2 HTTP/1.1
Authorization: Basic admin admin

### User admin:admin
POST http://dev.dictadata.org:8089/test/echo/xyzparam HTTP/1.1
Authorization: Basic admin admin
Content-Type: application/json; charset=utf-8

{
  "field1": "value1",
  "field2": 22
}
