### json_foofile > es_foo_schema_pk
POST http://dev.dictadata.net:8089/node/etl?fiber=foo_action HTTP/1.1
Authorization: Basic user user
Content-Type: application/json; charset=utf-8

{
  "fibers": [
    {
      "name": "foo_action",
      "action": "transfer",
      "origin": {
        "smt": ":json_foofile",
        "options": {}
      },
      "terminal": {
        "smt": ":es_foo_schema_pk",
        "options": {}
      }
    }
  ]
}

### csv_foofile => mysql_foo_schema
POST http://dev.dictadata.net:8089/node/etl HTTP/1.1
Authorization: Basic user user
Content-Type: application/json; charset=utf-8

{
  "origin": {
    "smt": ":csv_foofile",
    "options": {
      "header": true
    }
  },
  "terminal": {
    "smt": ":mysql_foo_schema",
    "options": {}
  }
}

### mysql_foo_schema => es_foo_transfer
POST http://dev.dictadata.net:8089/node/etl HTTP/1.1
Authorization: Basic user user
Content-Type: application/json; charset=utf-8

{
  "origin": {
    "smt": ":mysql_foo_schema",
    "options": {}
  },
  "terminal": {
    "smt": "foo:es_foo_transfer",
    "options": {}
  }
}

### es_foo_transfer => mysql_foo_transfer
POST http://dev.dictadata.net:8089/node/etl HTTP/1.1
Authorization: Basic user user
Content-Type: application/json; charset=utf-8

{
  "origin": {
    "smt": "foo:es_foo_transfer",
    "options": {}
  },
  "terminal": {
    "smt": "foo:mysql_foo_transfer",
    "options": {}
  }
}

### rest_weather_forecast => es_weather_forecast
POST http://dev.dictadata.net:8089/node/etl HTTP/1.1
Authorization: Basic user user
Content-Type: application/json; charset=utf-8

{
  "origin": {
    "smt": ":rest_weather_forecast",
    "options": {
        "headers": {
          "Accept": "application/ld+json",
          "User-Agent": "@dictadata.net/storage-node contact:info@dictadata.net"
        },
        "reader": {
          "pick": {
            "encoding": "",
            "data": "periods"
          }
        }
    }
  },
  "terminal": {
    "smt": ":es_weather_forecast",
    "options": {}
  }
}

### rest_weather_forecast => mysql_weather_forecast
POST http://dev.dictadata.net:8089/node/etl HTTP/1.1
Authorization: Basic user user
Content-Type: application/json; charset=utf-8

{
  "origin": {
    "smt": ":rest_weather_forecast",
    "options": {
        "headers": {
          "Accept": "application/ld+json",
          "User-Agent": "@dictadata.net/storage-node contact:info@dictadata.net"
        },
        "reader": {
          "pick": {
            "encoding": "",
            "data": "periods"
          }
        }
    }
  },
  "terminal": {
    "smt": ":mysql_weather_forecast",
    "options": {}
  }
}


### rest_weather_forecast => oracle_weather_forecast
POST http://dev.dictadata.net:8089/node/etl HTTP/1.1
Authorization: Basic user user
Content-Type: application/json; charset=utf-8

{
  "origin": {
    "smt": ":rest_weather_forecast",
    "options": {
        "headers": {
          "Accept": "application/ld+json",
          "User-Agent": "@dictadata.net/storage-node contact:info@dictadata.net"
        },
        "reader": {
          "pick": {
            "encoding": "",
            "data": "periods"
          }
        }
    }
  },
  "terminal": {
    "smt": ":oracle_weather_forecast",
    "options": {}
  }
}

### foo:foo_transfer
POST http://dev.dictadata.net:8089/node/etl/foo:foo_transfer HTTP/1.1
Authorization: Basic user user
Content-Type: application/json; charset=utf-8

### foo:foo_alias
POST http://dev.dictadata.net:8089/node/etl/foo:foo_alias HTTP/1.1
Authorization: Basic user user
Content-Type: application/json; charset=utf-8

### foo:foo_with_params
POST http://dev.dictadata.net:8089/node/etl/foo:foo_with_params?Foo=none HTTP/1.1
Authorization: Basic user user
Content-Type: application/json; charset=utf-8

### foo:foo_with_params
POST http://dev.dictadata.net:8089/node/etl/foo:foo_with_params?Foo=first HTTP/1.1
Authorization: Basic user user
Content-Type: application/json; charset=utf-8

### foo:bar_foreach
POST http://dev.dictadata.net:8089/node/etl/foo:bar_foreach?tag=bar&Foo=third HTTP/1.1
Authorization: Basic user user
Content-Type: application/json; charset=utf-8


### foo_cache_create
POST http://dev.dictadata.net:8089/node/etl/foo:foo_retrieve?fiber=create HTTP/1.1
Authorization: Basic user user
Content-Type: application/json; charset=utf-8

### foo_cache_dull
POST http://dev.dictadata.net:8089/node/etl/foo:foo_retrieve?fiber=dull HTTP/1.1
Authorization: Basic user user
Content-Type: application/json; charset=utf-8

### foo_cache_retrieve
POST http://dev.dictadata.net:8089/node/etl/foo:foo_retrieve?fiber=retrieve HTTP/1.1
Authorization: Basic user user
Content-Type: application/json; charset=utf-8
