### no Authorization header: unauthorized
GET http://dev.dictadata.org:8089/node/status/es_foo_schema_pk HTTP/1.1

### unregistered  Public
GET http://dev.dictadata.org:8089/node/status/es_foo_schema_pk HTTP/1.1
Authorization: Basic Aladdin opensesame

### guest  Public
GET http://dev.dictadata.org:8089/node/status/es_foo_schema_pk HTTP/1.1
Authorization: Basic guest guest

### user  User
GET http://dev.dictadata.org:8089/node/status/es_foo_schema_pk HTTP/1.1
Authorization: Basic user user

### user  User
GET http://dev.dictadata.org:8089/node/status/INVALID_SMT HTTP/1.1
Authorization: Basic user user

### user
GET http://dev.dictadata.org:8089/node/status/mysql_foo_schema HTTP/1.1
Authorization: Basic user user

### admin  Admin
GET http://dev.dictadata.org:8089/node/status/mysql_foo_schema HTTP/1.1
Authorization: Basic admin admin
