### es_foo_schema_pk
PUT http://localhost:8089/node/encoding/es_foo_schema_pk HTTP/1.1
Authorization: Basic user user
Content-Type: application/json; charset=utf-8

{
  "fields": {
    "Foo": {
      "name": "Foo",
      "type": "keyword",
      "size": 64,
      "default": null,
      "isNullable": false,
      "isKey": true,
      "label": "Foo"
    },
    "Bar": {
      "name": "Bar",
      "type": "keyword",
      "size": 64,
      "default": null,
      "isNullable": true,
      "isKey": false,
      "label": "Bar"
    },
    "Baz": {
      "name": "Baz",
      "type": "integer",
      "size": 0,
      "default": null,
      "isNullable": true,
      "isKey": false,
      "label": "Baz"
    },
    "Fobe": {
      "name": "Fobe",
      "type": "number",
      "size": 0,
      "default": null,
      "isNullable": true,
      "isKey": false,
      "label": "Fobe, ain't no Foo"
    },
    "Dt Test": {
      "name": "Dt Test",
      "type": "date",
      "size": 0,
      "default": null,
      "isNullable": true,
      "isKey": false,
      "label": "Dt Test"
    },
    "enabled": {
      "name": "enabled",
      "type": "boolean",
      "size": 0,
      "default": null,
      "isNullable": true,
      "isKey": false,
      "label": "enabled"
    }
  }
}

### es_foo_schema_pk
PUT http://localhost:8089/node/encoding HTTP/1.1
Authorization: Basic user user
Content-Type: application/json; charset=utf-8

{
  "SMT": "es_foo_schema_pk",
  "fields": {
    "Foo": {
      "name": "Foo",
      "type": "keyword",
      "size": 64,
      "default": null,
      "isNullable": false,
      "isKey": true,
      "label": "Foo"
    },
    "Bar": {
      "name": "Bar",
      "type": "keyword",
      "size": 64,
      "default": null,
      "isNullable": true,
      "isKey": false,
      "label": "Bar"
    },
    "Baz": {
      "name": "Baz",
      "type": "integer",
      "size": 0,
      "default": null,
      "isNullable": true,
      "isKey": false,
      "label": "Baz"
    },
    "Fobe": {
      "name": "Fobe",
      "type": "number",
      "size": 0,
      "default": null,
      "isNullable": true,
      "isKey": false,
      "label": "Fobe, ain't no Foo"
    },
    "Dt Test": {
      "name": "Dt Test",
      "type": "date",
      "size": 0,
      "default": null,
      "isNullable": true,
      "isKey": false,
      "label": "Dt Test"
    },
    "enabled": {
      "name": "enabled",
      "type": "boolean",
      "size": 0,
      "default": null,
      "isNullable": true,
      "isKey": false,
      "label": "enabled"
    }
  }
}

### mssql_foo_schema_pk
PUT http://localhost:8089/node/encoding/mssql_foo_schema_pk HTTP/1.1
Authorization: Basic admin admin
Content-Type: application/json; charset=utf-8

{
  "fields": {
    "Foo": {
      "name": "Foo",
      "type": "keyword",
      "size": 64,
      "default": null,
      "isNullable": false,
      "isKey": true,
      "label": "Foo"
    },
    "Bar": {
      "name": "Bar",
      "type": "keyword",
      "size": 64,
      "default": null,
      "isNullable": true,
      "isKey": false,
      "label": "Bar"
    },
    "Baz": {
      "name": "Baz",
      "type": "integer",
      "size": 0,
      "default": null,
      "isNullable": true,
      "isKey": false,
      "label": "Baz"
    },
    "Fobe": {
      "name": "Fobe",
      "type": "number",
      "size": 0,
      "default": null,
      "isNullable": true,
      "isKey": false,
      "label": "Fobe, ain't no Foo"
    },
    "Dt Test": {
      "name": "Dt Test",
      "type": "date",
      "size": 0,
      "default": null,
      "isNullable": true,
      "isKey": false,
      "label": "Dt Test"
    },
    "enabled": {
      "name": "enabled",
      "type": "boolean",
      "size": 0,
      "default": null,
      "isNullable": true,
      "isKey": false,
      "label": "enabled"
    }
  }
}

### mssql_foo_schema_pk
PUT http://localhost:8089/node/encoding HTTP/1.1
Authorization: Basic admin admin
Content-Type: application/json; charset=utf-8

{
  "SMT": "mssql_foo_schema_pk",
  "fields": {
    "Foo": {
      "name": "Foo",
      "type": "keyword",
      "size": 64,
      "default": null,
      "isNullable": false,
      "isKey": true,
      "label": "Foo"
    },
    "Bar": {
      "name": "Bar",
      "type": "keyword",
      "size": 64,
      "default": null,
      "isNullable": true,
      "isKey": false,
      "label": "Bar"
    },
    "Baz": {
      "name": "Baz",
      "type": "integer",
      "size": 0,
      "default": null,
      "isNullable": true,
      "isKey": false,
      "label": "Baz"
    },
    "Fobe": {
      "name": "Fobe",
      "type": "number",
      "size": 0,
      "default": null,
      "isNullable": true,
      "isKey": false,
      "label": "Fobe, ain't no Foo"
    },
    "Dt Test": {
      "name": "Dt Test",
      "type": "date",
      "size": 0,
      "default": null,
      "isNullable": true,
      "isKey": false,
      "label": "Dt Test"
    },
    "enabled": {
      "name": "enabled",
      "type": "boolean",
      "size": 0,
      "default": null,
      "isNullable": true,
      "isKey": false,
      "label": "enabled"
    }
  }
}

### mysql_foo_schema_pk
PUT http://localhost:8089/node/encoding/mysql_foo_schema_pk HTTP/1.1
Authorization: Basic admin admin
Content-Type: application/json; charset=utf-8

{
  "fields": {
    "Foo": {
      "name": "Foo",
      "type": "keyword",
      "size": 64,
      "default": null,
      "isNullable": false,
      "isKey": true,
      "label": "Foo"
    },
    "Bar": {
      "name": "Bar",
      "type": "keyword",
      "size": 64,
      "default": null,
      "isNullable": true,
      "isKey": false,
      "label": "Bar"
    },
    "Baz": {
      "name": "Baz",
      "type": "integer",
      "size": 0,
      "default": null,
      "isNullable": true,
      "isKey": false,
      "label": "Baz"
    },
    "Fobe": {
      "name": "Fobe",
      "type": "number",
      "size": 0,
      "default": null,
      "isNullable": true,
      "isKey": false,
      "label": "Fobe, ain't no Foo"
    },
    "Dt Test": {
      "name": "Dt Test",
      "type": "date",
      "size": 0,
      "default": null,
      "isNullable": true,
      "isKey": false,
      "label": "Dt Test"
    },
    "enabled": {
      "name": "enabled",
      "type": "boolean",
      "size": 0,
      "default": null,
      "isNullable": true,
      "isKey": false,
      "label": "enabled"
    }
  }
}

### mysql_foo_schema_pk
PUT http://localhost:8089/node/encoding HTTP/1.1
Authorization: Basic admin admin
Content-Type: application/json; charset=utf-8

{
  "SMT": "mysql_foo_schema_pk",
  "fields": {
    "Foo": {
      "name": "Foo",
      "type": "keyword",
      "size": 64,
      "default": null,
      "isNullable": false,
      "isKey": true,
      "label": "Foo"
    },
    "Bar": {
      "name": "Bar",
      "type": "keyword",
      "size": 64,
      "default": null,
      "isNullable": true,
      "isKey": false,
      "label": "Bar"
    },
    "Baz": {
      "name": "Baz",
      "type": "integer",
      "size": 0,
      "default": null,
      "isNullable": true,
      "isKey": false,
      "label": "Baz"
    },
    "Fobe": {
      "name": "Fobe",
      "type": "number",
      "size": 0,
      "default": null,
      "isNullable": true,
      "isKey": false,
      "label": "Fobe, ain't no Foo"
    },
    "Dt Test": {
      "name": "Dt Test",
      "type": "date",
      "size": 0,
      "default": null,
      "isNullable": true,
      "isKey": false,
      "label": "Dt Test"
    },
    "enabled": {
      "name": "enabled",
      "type": "boolean",
      "size": 0,
      "default": null,
      "isNullable": true,
      "isKey": false,
      "label": "enabled"
    }
  }
}


### oracle_foo_schema_pk
PUT http://localhost:8089/node/encoding/oracle_foo_schema_pk HTTP/1.1
Authorization: Basic admin admin
Content-Type: application/json; charset=utf-8

{
  "fields": {
    "Foo": {
      "name": "Foo",
      "type": "keyword",
      "size": 64,
      "default": null,
      "isNullable": false,
      "isKey": true,
      "label": "Foo"
    },
    "Bar": {
      "name": "Bar",
      "type": "keyword",
      "size": 64,
      "default": null,
      "isNullable": true,
      "isKey": false,
      "label": "Bar"
    },
    "Baz": {
      "name": "Baz",
      "type": "integer",
      "size": 0,
      "default": null,
      "isNullable": true,
      "isKey": false,
      "label": "Baz"
    },
    "Fobe": {
      "name": "Fobe",
      "type": "number",
      "size": 0,
      "default": null,
      "isNullable": true,
      "isKey": false,
      "label": "Fobe, ain't no Foo"
    },
    "Dt Test": {
      "name": "Dt Test",
      "type": "date",
      "size": 0,
      "default": null,
      "isNullable": true,
      "isKey": false,
      "label": "Dt Test"
    },
    "enabled": {
      "name": "enabled",
      "type": "boolean",
      "size": 0,
      "default": null,
      "isNullable": true,
      "isKey": false,
      "label": "enabled"
    }
  }
}

### oracle_foo_schema_pk
PUT http://localhost:8089/node/encoding HTTP/1.1
Authorization: Basic admin admin
Content-Type: application/json; charset=utf-8

{
  "SMT": "oracle_foo_schema_pk",
  "fields": {
    "Foo": {
      "name": "Foo",
      "type": "keyword",
      "size": 64,
      "default": null,
      "isNullable": false,
      "isKey": true,
      "label": "Foo"
    },
    "Bar": {
      "name": "Bar",
      "type": "keyword",
      "size": 64,
      "default": null,
      "isNullable": true,
      "isKey": false,
      "label": "Bar"
    },
    "Baz": {
      "name": "Baz",
      "type": "integer",
      "size": 0,
      "default": null,
      "isNullable": true,
      "isKey": false,
      "label": "Baz"
    },
    "Fobe": {
      "name": "Fobe",
      "type": "number",
      "size": 0,
      "default": null,
      "isNullable": true,
      "isKey": false,
      "label": "Fobe, ain't no Foo"
    },
    "Dt Test": {
      "name": "Dt Test",
      "type": "date",
      "size": 0,
      "default": null,
      "isNullable": true,
      "isKey": false,
      "label": "Dt Test"
    },
    "enabled": {
      "name": "enabled",
      "type": "boolean",
      "size": 0,
      "default": null,
      "isNullable": true,
      "isKey": false,
      "label": "enabled"
    }
  }
}
