### json_foofile > es_foo_schema_pk
POST http://dev.dictadata.org:8089/node/transfer HTTP/1.1
Authorization: Basic user user
Content-Type: application/json; charset=utf-8

{
  "tract": {
    "origin": {
      "smt": ":json_foofile",
      "options": {}
    },
    "terminal": {
      "smt": ":es_foo_schema_pk",
      "options": {}
    }
  }
}

### csv_foofile => mysql_foo_schema
POST http://dev.dictadata.org:8089/node/transfer HTTP/1.1
Authorization: Basic user user
Content-Type: application/json; charset=utf-8

{
  "origin": {
    "smt": ":csv_foofile",
    "options": {
      "header": true
    }
  },
  "terminal": {
    "smt": ":mysql_foo_schema",
    "options": {}
  }
}

### mysql_foo_schema => es_foo_transfer
POST http://dev.dictadata.org:8089/node/transfer HTTP/1.1
Authorization: Basic user user
Content-Type: application/json; charset=utf-8

{
  "origin": {
    "smt": ":mysql_foo_schema",
    "options": {}
  },
  "terminal": {
    "smt": ":es_foo_transfer",
    "options": {}
  }
}

### es_foo_schema_pk => mysql_foo_transfer
POST http://dev.dictadata.org:8089/node/transfer HTTP/1.1
Authorization: Basic user user
Content-Type: application/json; charset=utf-8

{
  "origin": {
    "smt": ":es_foo_schema_pk",
    "options": {}
  },
  "terminal": {
    "smt": ":mysql_foo_transfer",
    "options": {}
  },
  "transforms": {
    "mutate": {
      "map": {
        "Foo": "Foo",
        "Bar": "Bar",
        "Baz": "Baz",
        "Fobe": "Fobe",
        "Dt Test": "Dt Test",
        "enabled": "enabled"
      }
    }
  }
}

### rest_weather_forecast => es_weather_forecast
POST http://dev.dictadata.org:8089/node/transfer HTTP/1.1
Authorization: Basic user user
Content-Type: application/json; charset=utf-8

{
  "origin": {
    "smt": ":rest_weather_forecast",
    "options": {
        "headers": {
          "Accept": "application/ld+json",
          "User-Agent": "@dictadata.org/storage-node contact:info@dictadata.org"
        },
        "reader": {
          "extract": {
            "encoding": "",
            "data": "periods"
          }
        }
    }
  },
  "terminal": {
    "smt": ":es_weather_forecast",
    "options": {}
  }
}

### rest_weather_forecast => mssql_weather_forecast
POST http://dev.dictadata.org:8089/node/transfer HTTP/1.1
Authorization: Basic user user
Content-Type: application/json; charset=utf-8

{
  "origin": {
    "smt": ":rest_weather_forecast",
    "options": {
        "headers": {
          "Accept": "application/ld+json",
          "User-Agent": "@dictadata.org/storage-node contact:info@dictadata.org"
        },
        "reader": {
          "extract": {
            "encoding": "",
            "data": "periods"
          }
        }
    }
  },
  "terminal": {
    "smt": ":mssql_weather_forecast",
    "options": {}
  }
}

### rest_weather_forecast => mysql_weather_forecast
POST http://dev.dictadata.org:8089/node/transfer HTTP/1.1
Authorization: Basic user user
Content-Type: application/json; charset=utf-8

{
  "origin": {
    "smt": ":rest_weather_forecast",
    "options": {
        "headers": {
          "Accept": "application/ld+json",
          "User-Agent": "@dictadata.org/storage-node contact:info@dictadata.org"
        },
        "reader": {
          "extract": {
            "encoding": "",
            "data": "periods"
          }
        }
    }
  },
  "terminal": {
    "smt": ":mysql_weather_forecast",
    "options": {}
  }
}


### rest_weather_forecast => oracle_weather_forecast
POST http://dev.dictadata.org:8089/node/transfer HTTP/1.1
Authorization: Basic user user
Content-Type: application/json; charset=utf-8

{
  "origin": {
    "smt": ":rest_weather_forecast",
    "options": {
        "headers": {
          "Accept": "application/ld+json",
          "User-Agent": "@dictadata.org/storage-node contact:info@dictadata.org"
        },
        "reader": {
          "extract": {
            "encoding": "",
            "data": "periods"
          }
        }
    }
  },
  "terminal": {
    "smt": ":oracle_weather_forecast",
    "options": {}
  }
}
