### mysql_foo_schema_pk => es_foo_transform
POST http://localhost:8089/node/transfer HTTP/1.1
Authorization: Basic user user
Content-Type: application/json; charset=utf-8

{
  "origin": {
    "SMT": "mysql_foo_schema_pk",
    "options": {}
  },
  "terminal": {
    "SMT": "es_foo_transform",
    "options": {}
  },
  "transforms": {
    "filter": {
      "match": {
        "Bar": "row"
      },
      "drop": {
        "Baz": { "eq": 456 }
      }
    },
    "select": {
      "inject_before": {
        "Fie": "where's es fum?"
      },
      "fields": {
        "Foo": "Foo",
        "Bar": "Bar",
        "Baz": "Bazzy"
      }
    }
  }
}

### es_foo_schema_pk => mssql_foo_transform
POST http://localhost:8089/node/transfer HTTP/1.1
Authorization: Basic user user
Content-Type: application/json; charset=utf-8

{
  "origin": {
    "SMT": "es_foo_schema_pk",
    "options": {}
  },
  "terminal": {
    "SMT": "mssql_foo_transform",
    "options": {}
  },
  "transforms": {
    "filter": {
      "match": {
        "Bar": "row"
      },
      "drop": {
        "Baz": { "eq": 456 }
      }
    },
    "select": {
      "inject_after": {
        "Fie": "where's my fum?"
      },
      "fields": {
        "Foo": "Foo",
        "Bar": "Bar",
        "Bazzy": "Bazzy"
      }
    }
  }
}

### es_foo_schema_pk => mysql_foo_transform
POST http://localhost:8089/node/transfer HTTP/1.1
Authorization: Basic user user
Content-Type: application/json; charset=utf-8

{
  "origin": {
    "SMT": "es_foo_schema_pk",
    "options": {}
  },
  "terminal": {
    "SMT": "mysql_foo_transform",
    "options": {}
  },
  "transforms": {
    "filter": {
      "match": {
        "Bar": "row"
      },
      "drop": {
        "Baz": { "eq": 456 }
      }
    },
    "select": {
      "inject_after": {
        "Fie": "where's my fum?"
      },
      "fields": {
        "Foo": "Foo",
        "Bar": "Bar",
        "Bazzy": "Bazzy"
      }
    }
  }
}

### es_foo_schema_pk => oracle_foo_transform
POST http://localhost:8089/node/transfer HTTP/1.1
Authorization: Basic user user
Content-Type: application/json; charset=utf-8

{
  "origin": {
    "SMT": "es_foo_schema_pk",
    "options": {}
  },
  "terminal": {
    "SMT": "oracle_foo_transform",
    "options": {}
  },
  "transforms": {
    "filter": {
      "match": {
        "Bar": "row"
      },
      "drop": {
        "Baz": { "eq": 456 }
      }
    },
    "select": {
      "inject_after": {
        "Fie": "where's my fum?"
      },
      "fields": {
        "Foo": "Foo",
        "Bar": "Bar",
        "Bazzy": "Bazzy"
      }
    }
  }
}
