### es_foo_schema
### if array list then elasticsearch generates the key
PUT http://dev.dictadata.org:8089/node/store/es_foo_schema HTTP/1.1
Authorization: Basic user user
Content-Type: application/json; charset=utf-8

{
  "data": [{
    "Foo": "one",
    "Bar": "row",
    "Baz": 1,
    "Fobe": 1.1,
    "Dt Test": "2020-01-01T08:00:00",
    "enabled": true
  }]
}

### es_foo_schema
### if dictionary object then property names are the keys
PUT http://dev.dictadata.org:8089/node/store/es_foo_schema HTTP/1.1
Authorization: Basic user user
Content-Type: application/json; charset=utf-8

{
  "data": {
    "fifty": {
      "Foo": "fifty",
      "Bar": "Grant",
      "Baz": 50,
      "Fobe": 50.5,
      "Dt Test": "2022-05-05T08:00:00",
      "enabled": true
    }
  }
}

### es_foo_schema
### defined key is in construct["Foo"]
PUT http://dev.dictadata.org:8089/node/store/es_foo_schema HTTP/1.1
Authorization: Basic user user
Content-Type: application/json; charset=utf-8

{
  "data": [{
    "Foo": "ten",
    "Bar": "row",
    "Baz": 10,
    "Fobe": 10.10,
    "Dt Test": "2018-10-07T00:00:00.000Z",
    "enabled": true
  }]
}

### es_foo_schema_pk
### store multiple rows
PUT http://dev.dictadata.org:8089/node/store HTTP/1.1
Authorization: Basic user user
Content-Type: application/json; charset=utf-8

{
  "SMT": "es_foo_schema_pk",
  "data": [{
    "Foo": "eleventy",
    "Bar": "row",
    "Baz": 11,
    "Fobe": 11.11,
    "Dt Test": "2011-10-07T08:00:00",
    "enabled": true
  },{
    "Foo": "twelvety",
    "Bar": "row",
    "Baz": 12,
    "Fobe": 12.12,
    "Dt Test": "2012-03-03T08:00:00",
    "enabled": true
  }]
}


### mssql_foo_schema
PUT http://dev.dictadata.org:8089/node/store/mssql_foo_schema HTTP/1.1
Authorization: Basic user user
Content-Type: application/json; charset=utf-8

{
  "data": [{
    "Foo": "fifty",
    "Bar": "Grant",
    "Baz": 50,
    "Fobe": 50.5,
    "Dt Test": "2022-05-05T00:00:00.000Z",
    "enabled": true
  }]
}

### mssql_foo_schema
### store multiple rows
PUT http://dev.dictadata.org:8089/node/store/mssql_foo_schema HTTP/1.1
Authorization: Basic user user
Content-Type: application/json; charset=utf-8

{
  "data": [{
    "Foo": "eleventy",
    "Bar": "row",
    "Baz": 11,
    "Fobe": 11.11,
    "Dt Test": "2020-11-04T08:00:00",
    "enabled": true
  },{
    "Foo": "twelvety",
    "Bar": "row",
    "Baz": 12,
    "Fobe": 12.12,
    "Dt Test": "2020-12-03T08:00:00",
    "enabled": true
  }]
}


### mysql_foo_schema
PUT http://dev.dictadata.org:8089/node/store/mysql_foo_schema HTTP/1.1
Authorization: Basic user user
Content-Type: application/json; charset=utf-8

{
  "data": [{
    "Foo": "fifty",
    "Bar": "Grant",
    "Baz": 50,
    "Fobe": 50.5,
    "Dt Test": "2020-05-05T08:00:00.000Z",
    "enabled": true
  }]
}

### mysql_foo_schema
### store multiple rows
PUT http://dev.dictadata.org:8089/node/store/mysql_foo_schema HTTP/1.1
Authorization: Basic user user
Content-Type: application/json; charset=utf-8

{
  "data": [{
    "Foo": "eleventy",
    "Bar": "row",
    "Baz": 11,
    "Fobe": 11.11,
    "Dt Test": "2020-11-04T08:00:00",
    "enabled": true
  },{
    "Foo": "twelvety",
    "Bar": "row",
    "Baz": 12,
    "Fobe": 12.12,
    "Dt Test": "2020-12-03T08:00:00",
    "enabled": true
  }]
}


### oracle_foo_schema
PUT http://dev.dictadata.org:8089/node/store/oracle_foo_schema HTTP/1.1
Authorization: Basic user user
Content-Type: application/json; charset=utf-8

{
  "data": [{
    "Foo": "fifty",
    "Bar": "Grant",
    "Baz": 50,
    "Fobe": 50.5,
    "Dt Test": "2022-05-05T08:00:00.000Z",
    "enabled": true
  }]
}

### oracle_foo_schema
### store multiple rows
PUT http://dev.dictadata.org:8089/node/store/oracle_foo_schema HTTP/1.1
Authorization: Basic user user
Content-Type: application/json; charset=utf-8

{
  "data": [{
    "Foo": "eleventy",
    "Bar": "row",
    "Baz": 11,
    "Fobe": 11.11,
    "Dt Test": "2020-11-04T08:00:00",
    "enabled": true
  },{
    "Foo": "twelvety",
    "Bar": "row",
    "Baz": 12,
    "Fobe": 12.12,
    "Dt Test": "2020-12-03T08:00:00",
    "enabled": true
  }]
}
