### es_foo_schema
POST http://dev.dictadata.net:8089/node/retrieve/:es_foo_schema HTTP/1.1
Authorization: Basic user user
Content-Type: application/json; charset=utf-8

{
  "pattern": {
    "match": {
      "Baz": { "gte": 0, "lte": 5000 }
    },
    "aggregate": {
      "Foo": {
        "baz_sum": { "sum": "Baz" },
        "count": { "count": "Baz" },
        "dt_min": { "min": "Dt Test" },
        "dt_max": { "max": "Dt Test" }
      }
    },
    "count": 3,
    "order": {"baz_sum": "desc"}
  }
}

### mysql_foo_schema
POST http://dev.dictadata.net:8089/node/retrieve/:mysql_foo_schema HTTP/1.1
Authorization: Basic user user
Content-Type: application/json; charset=utf-8

{
  "pattern": {
    "match": {
      "Baz": { "gte": 0, "lte": 5000 }
    },
    "aggregate": {
      "Foo": {
        "baz_sum": { "sum": "Baz" },
        "count": { "count": "Baz" },
        "dt_min": { "min": "Dt Test" },
        "dt_max": { "max": "Dt Test" }
      }
    },
    "count": 3,
    "order": {"baz_sum": "desc"}
   }
}

### oracle_foo_schema
POST http://dev.dictadata.net:8089/node/retrieve/oracle_foo_schema HTTP/1.1
Authorization: Basic user user
Content-Type: application/json; charset=utf-8

{
  "pattern": {
    "match": {
      "Baz": { "gte": 0, "lte": 5000 }
    },
    "aggregate": {
      "Foo": {
        "baz_sum": { "sum": "Baz" },
        "count": { "count": "Baz" },
        "dt_min": { "min": "Dt Test" },
        "dt_max": { "max": "Dt Test" }
      }
    },
    "count": 3,
    "order": {"baz_sum": "desc"}
   }
}
