### es_foo_schema_x
POST http://dev.dictadata.net:8089/node/list/:es_foo_schema_x HTTP/1.1
Authorization: Basic admin admin

### es_foo_schema_pk
POST http://dev.dictadata.net:8089/node/list/:es_foo_schema_pk HTTP/1.1
Authorization: Basic admin admin

### es_foo_schema_pk
POST http://dev.dictadata.net:8089/node/list/:es_foo_schema_pk?schema=* HTTP/1.1
Authorization: Basic admin admin

### es_foo_schema_pk
POST http://dev.dictadata.net:8089/node/list HTTP/1.1
Authorization: Basic admin admin
Content-Type: application/json; charset=utf-8

{
  "smt": ":es_foo_schema_pk",
  "schema": "foo*"
}

### :es_foo_schema_origin
POST http://dev.dictadata.net:8089/node/list/:es_foo_schema_origin HTTP/1.1
Authorization: Basic user user
Content-Type: application/json; charset=utf-8

{
  "schema": "foo*"
}


### mssql_foo_schema
POST http://dev.dictadata.net:8089/node/list/:mssql_foo_schema HTTP/1.1
Authorization: Basic admin admin

### mssql_foo_schema *
POST http://dev.dictadata.net:8089/node/list/:mssql_foo_schema?schema=* HTTP/1.1
Authorization: Basic admin admin

### mssql_foo_schema foo*
POST http://dev.dictadata.net:8089/node/list HTTP/1.1
Authorization: Basic admin admin
Content-Type: application/json; charset=utf-8

{
  "smt": ":mssql_foo_schema",
  "schema": "foo*"
}


### mysql_foo_schema
POST http://dev.dictadata.net:8089/node/list/:mysql_foo_schema HTTP/1.1
Authorization: Basic admin admin

### mysql_foo_schema *
POST http://dev.dictadata.net:8089/node/list/:mysql_foo_schema?schema=* HTTP/1.1
Authorization: Basic admin admin

### mysql_foo_schema foo*
POST http://dev.dictadata.net:8089/node/list HTTP/1.1
Authorization: Basic admin admin
Content-Type: application/json; charset=utf-8

{
  "smt": ":mysql_foo_schema",
  "schema": "foo*"
}

### :mysql_foo_schema_origin
POST http://dev.dictadata.net:8089/node/list/:mysql_foo_schema_origin HTTP/1.1
Authorization: Basic user user
Content-Type: application/json; charset=utf-8

{
  "schema": "foo*"
}


### oracle_foo_schema
POST http://dev.dictadata.net:8089/node/list/oracle_foo_schema HTTP/1.1
Authorization: Basic admin admin

### oracle_foo_schema *
POST http://dev.dictadata.net:8089/node/list/oracle_foo_schema?schema=* HTTP/1.1
Authorization: Basic admin admin

### oracle_foo_schema foo*
POST http://dev.dictadata.net:8089/node/list HTTP/1.1
Authorization: Basic admin admin
Content-Type: application/json; charset=utf-8

{
  "smt": ":oracle_foo_schema",
  "schema": "foo*"
}
