### es_foo_schema_id
DELETE http://dev.dictadata.net:8089/node/dull/:es_foo_schema_id HTTP/1.1
Authorization: Basic user user

### es_foo_schema
DELETE http://dev.dictadata.net:8089/node/dull/:es_foo_schema HTTP/1.1
Authorization: Basic user user
Content-Type: application/json; charset=utf-8

{
    "key": "fifty"
}

### es_foo_schema
DELETE http://dev.dictadata.net:8089/node/dull/:es_foo_schema HTTP/1.1
Authorization: Basic user user
Content-Type: application/json; charset=utf-8

{
    "Foo": "ten"
}

### es_foo_schema_pk
DELETE http://dev.dictadata.net:8089/node/dull HTTP/1.1
Authorization: Basic user user
Content-Type: application/json; charset=utf-8

{
  "smt": ":es_foo_schema_pk",
  "pattern": {
    "match": {
      "Foo": "twelvety"
    }
  }
}


### mssql_foo_schema
DELETE http://dev.dictadata.net:8089/node/dull/:mssql_foo_schema HTTP/1.1
Authorization: Basic user user
Content-Type: application/json; charset=utf-8

{
  "pattern": {
    "match": {
      "Foo": "eleventy"
    }
  }
}

### mysql_foo_schema
DELETE http://dev.dictadata.net:8089/node/dull/:mysql_foo_schema HTTP/1.1
Authorization: Basic user user
Content-Type: application/json; charset=utf-8

{
  "pattern": {
    "match": {
      "Foo": "eleventy"
    }
  }
}

### oracle_foo_schema
DELETE http://dev.dictadata.net:8089/node/dull/oracle_foo_schema HTTP/1.1
Authorization: Basic user user
Content-Type: application/json; charset=utf-8

{
  "pattern": {
    "match": {
      "Foo": "eleventy"
    }
  }
}
