### es_foo_schema_x
GET http://dev.dictadata.net:8089/node/schema/:es_foo_schema_x HTTP/1.1
Authorization: Basic admin admin

### es_foo_schema_pk
GET http://dev.dictadata.net:8089/node/schema/:es_foo_schema_pk HTTP/1.1
Authorization: Basic admin admin

### es_foo_schema_pk
GET http://dev.dictadata.net:8089/node/schema HTTP/1.1
Authorization: Basic admin admin
Content-Type: application/json; charset=utf-8

{
  "smt": ":es_foo_schema_pk"
}

### accounts
### accounts is a development only SMT
GET http://dev.dictadata.net:8089/node/schema HTTP/1.1
Authorization: Basic admin admin
Content-Type: application/json; charset=utf-8

{
  "smt": ":accounts"
}

### mssql_foo_schema
GET http://dev.dictadata.net:8089/node/schema/:mssql_foo_schema HTTP/1.1
Authorization: Basic admin admin

### mysql_foo_schema
GET http://dev.dictadata.net:8089/node/schema/:mysql_foo_schema HTTP/1.1
Authorization: Basic admin admin

### oracle_foo_schema
GET http://dev.dictadata.net:8089/node/schema/:oracle_foo_schema HTTP/1.1
Authorization: Basic admin admin
