### es_foo_schema_pk
POST http://localhost:8089/node/list/es_foo_schema_pk HTTP/1.1
Authorization: Basic admin admin

### es_foo_schema_pk
POST http://localhost:8089/node/list/es_foo_schema_pk?schema=* HTTP/1.1
Authorization: Basic admin admin

### es_foo_schema_pk
POST http://localhost:8089/node/list HTTP/1.1
Authorization: Basic admin admin
Content-Type: application/json;charset=utf-8

{
  "SMT": "es_foo_schema_pk",
  "schema": "foo*"
}


### mssql_foo_schema_pk
POST http://localhost:8089/node/list/mssql_foo_schema_pk HTTP/1.1
Authorization: Basic admin admin

### mssql_foo_schema_pk *
POST http://localhost:8089/node/list/mssql_foo_schema_pk?schema=* HTTP/1.1
Authorization: Basic admin admin

### mssql_foo_schema_pk foo*
POST http://localhost:8089/node/list HTTP/1.1
Authorization: Basic admin admin
Content-Type: application/json;charset=utf-8

{
  "SMT": "mssql_foo_schema_pk",
  "schema": "foo*"
}


### mysql_foo_schema_pk
POST http://localhost:8089/node/list/mysql_foo_schema_pk HTTP/1.1
Authorization: Basic admin admin

### mysql_foo_schema_pk *
POST http://localhost:8089/node/list/mysql_foo_schema_pk?schema=* HTTP/1.1
Authorization: Basic admin admin

### mysql_foo_schema_pk foo*
POST http://localhost:8089/node/list HTTP/1.1
Authorization: Basic admin admin
Content-Type: application/json;charset=utf-8

{
  "SMT": "mysql_foo_schema_pk",
  "schema": "foo*"
}



### oracle_foo_schema_pk
POST http://localhost:8089/node/list/oracle_foo_schema_pk HTTP/1.1
Authorization: Basic admin admin

### oracle_foo_schema_pk *
POST http://localhost:8089/node/list/oracle_foo_schema_pk?schema=* HTTP/1.1
Authorization: Basic admin admin

### oracle_foo_schema_pk foo*
POST http://localhost:8089/node/list HTTP/1.1
Authorization: Basic admin admin
Content-Type: application/json;charset=utf-8

{
  "SMT": "oracle_foo_schema_pk",
  "schema": "foo*"
}
