### es_foo_schema_id
GET http://localhost:8089/node/recall/es_foo_schema_id HTTP/1.1
Authorization: Basic admin admin

### es_foo_schema
GET http://localhost:8089/node/recall/es_foo_schema HTTP/1.1
Authorization: Basic admin admin
Content-Type: application/json; charset=utf-8

{
  "key": "fifty"
}

### es_foo_schema
GET http://localhost:8089/node/recall/es_foo_schema HTTP/1.1
Authorization: Basic admin admin
Content-Type: application/json; charset=utf-8

{
  "Foo": "ten"
}

### es_foo_schema_pk
GET http://localhost:8089/node/recall HTTP/1.1
Authorization: Basic admin admin
Content-Type: application/json; charset=utf-8

{
  "SMT": "es_foo_schema_pk",
  "pattern": {
    "match": {
      "Foo": "fifty"
    }
  }
}

### mssql_foo_schema
GET http://localhost:8089/node/recall/mssql_foo_schema HTTP/1.1
Authorization: Basic admin admin
Content-Type: application/json; charset=utf-8

{
  "pattern": {
    "match": {
      "Foo": "fifty"
    }
  }
}

### mysql_foo_schema
GET http://localhost:8089/node/recall/mysql_foo_schema HTTP/1.1
Authorization: Basic admin admin
Content-Type: application/json; charset=utf-8

{
  "pattern": {
    "match": {
      "Foo": "fifty"
    }
  }
}


### oracle_foo_schema
GET http://localhost:8089/node/recall/oracle_foo_schema HTTP/1.1
Authorization: Basic admin admin
Content-Type: application/json; charset=utf-8

{
  "pattern": {
    "match": {
      "Foo": "fifty"
    }
  }
}

