### es_foo_schema
POST http://localhost:8089/node/retrieve/es_foo_schema HTTP/1.1
Authorization: Basic user user
Content-Type: application/json; charset=utf-8

{
  "pattern": {
    "order": {"Foo": "asc"},
    "count": 100
  }
}

### es_foo_schema_ks
POST http://localhost:8089/node/retrieve HTTP/1.1
Authorization: Basic user user
Content-Type: application/json; charset=utf-8

{
  "SMT": "es_foo_schema_ks",
  "pattern": {
    "match": {
      "Foo": "twenty"
    }
  }
}

### es_foo_schema_pk
POST http://localhost:8089/node/retrieve/es_foo_schema_pk HTTP/1.1
Authorization: Basic user user
Content-Type: application/json; charset=utf-8

{
  "pattern": {
    "match": {
      "Bar": "row",
      "Baz": { "gte": 100, "lte": 500 }
    },
    "count": 3,
    "order": {"Foo": "asc"}
  }
}


### mssql_foo_schema
POST http://localhost:8089/node/retrieve/mssql_foo_schema HTTP/1.1
Authorization: Basic user user
Content-Type: application/json; charset=utf-8

{
}

### mssql_foo_schema
POST http://localhost:8089/node/retrieve/mssql_foo_schema HTTP/1.1
Authorization: Basic user user
Content-Type: application/json; charset=utf-8

{
  "pattern": {
    "match": {
      "Foo": "twenty"
    }
  }
}

### mssql_foo_schema
POST http://localhost:8089/node/retrieve/mssql_foo_schema HTTP/1.1
Authorization: Basic user user
Content-Type: application/json; charset=utf-8

{
  "pattern": {
    "match": {
      "Bar": "row",
      "Baz": { "gte": 10, "lte": 500 }
    },
    "count": 3,
    "order": {"Dt Test": "desc"}
  }
}


### mysql_foo_schema
POST http://localhost:8089/node/retrieve/mysql_foo_schema HTTP/1.1
Authorization: Basic user user
Content-Type: application/json; charset=utf-8

{
}

### mysql_foo_schema
POST http://localhost:8089/node/retrieve/mysql_foo_schema HTTP/1.1
Authorization: Basic user user
Content-Type: application/json; charset=utf-8

{
  "pattern": {
    "match": {
      "Foo": "twenty"
    }
  }
}

### mysql_foo_schema
POST http://localhost:8089/node/retrieve/mysql_foo_schema HTTP/1.1
Authorization: Basic user user
Content-Type: application/json; charset=utf-8

{
  "pattern": {
    "match": {
      "Bar": "row",
      "Baz": { "gte": 10, "lte": 500 }
    },
    "count": 3,
    "order": {"Dt Test": "desc"}
  }
}


### oracle_foo_schema
POST http://localhost:8089/node/retrieve/oracle_foo_schema HTTP/1.1
Authorization: Basic user user
Content-Type: application/json; charset=utf-8

{
}

### oracle_foo_schema
POST http://localhost:8089/node/retrieve/oracle_foo_schema HTTP/1.1
Authorization: Basic user user
Content-Type: application/json; charset=utf-8

{
  "pattern": {
    "match": {
      "Foo": "twenty"
    }
  }
}

### oracle_foo_schema
POST http://localhost:8089/node/retrieve/oracle_foo_schema HTTP/1.1
Authorization: Basic user user
Content-Type: application/json; charset=utf-8

{
  "pattern": {
    "match": {
      "Bar": "row",
      "Baz": { "gte": 10, "lte": 500 }
    },
    "count": 3,
    "order": {"Dt Test": "desc"}
  }
}
