### not found
GET http://dev.dictadata.net:8089/node/tracts/foo_transfer
Authorization: Basic user user

### not found
GET http://dev.dictadata.net:8089/node/tracts/:foo_transfer
Authorization: Basic user user

### OK
GET http://dev.dictadata.net:8089/node/tracts/foo:foo_transfer
Authorization: Basic user user

### OK
GET http://dev.dictadata.net:8089/node/tracts/foo:foo_alias
Authorization: Basic user user

### OK
GET http://dev.dictadata.net:8089/node/tracts/foo:foo_alias?resolve=true
Authorization: Basic user user

### OK
GET http://dev.dictadata.net:8089/node/tracts/foo:foo_with_params
Authorization: Basic user user

###
POST http://dev.dictadata.net:8089/node/tracts
Authorization: Basic user user
Content-Type: application/json; charset=utf-8

{
  "pattern": {
    "match": {
      "name": {
        "wc": "foo_transfer*"
      }
    }
  }
}

###
POST http://dev.dictadata.net:8089/node/tracts
Authorization: Basic user user
Content-Type: application/json; charset=utf-8

{
  "pattern": {
    "match": {
      "name": {
        "eq": "tigerline"
      }
    }
  }
}

###
DELETE http://dev.dictadata.net:8089/node/tracts/foo:foo_transfer_XYZ
Authorization: Basic user user

###
PUT http://dev.dictadata.net:8089/node/tracts
Authorization: Basic user user
Content-Type: application/json; charset=utf-8

{
  "realm": "foo",
  "name": "foo_transfer_XYZ",
  "type": "engram",
  "title": "foo_transfer encoding",
  "description": "test input for foo_transfer_XYZ encoding",
  "source": "file:./test/data/input/engrams/foo_transfer_XYZ.engram.json",
  "tags": [
    "foo"
  ],
  "actions": []
}
