### mysql_foo_schema => es_foo_transform
POST http://dev.dictadata.net:8089/node/etl HTTP/1.1
Authorization: Basic user user
Content-Type: application/json; charset=utf-8

{
  "origin": {
    "smt": ":mysql_foo_schema",
    "options": {}
  },
  "terminal": {
    "smt": ":es_foo_transform",
    "options": {}
  },
  "transforms": [
    {
      "transform": "filter",
      "match": {
        "Bar": "row"
      },
      "drop": {
        "Baz": { "eq": 456 }
      }
    },
    {
      "transform": "mutate",
      "default": {
        "Fie": "where's es fum?"
      },
      "map": {
        "Foo": "Foo",
        "Bar": "Bar",
        "Baz": "Bazzy"
      }
    }
  ]
}

### es_foo_schema_pk => mysql_foo_transform
POST http://dev.dictadata.net:8089/node/etl HTTP/1.1
Authorization: Basic user user
Content-Type: application/json; charset=utf-8

{
  "origin": {
    "smt": ":es_foo_schema_pk",
    "options": {}
  },
  "terminal": {
    "smt": ":mysql_foo_transform",
    "options": {}
  },
  "transforms": [
    {
      "transform": "filter",
      "match": {
        "Bar": "row"
      },
      "drop": {
        "Baz": { "eq": 456 }
      }
    },
    {
      "transform": "mutate",
      "override": {
        "Fie": "where's my fum?"
      },
      "map": {
        "Foo": "Foo",
        "Bar": "Bar",
        "Bazzy": "Bazzy"
      }
    }
  ]
}

### es_foo_schema_pk => oracle_foo_transform
POST http://dev.dictadata.net:8089/node/etl HTTP/1.1
Authorization: Basic user user
Content-Type: application/json; charset=utf-8

{
  "origin": {
    "smt": ":es_foo_schema_pk",
    "options": {}
  },
  "terminal": {
    "smt": ":oracle_foo_transform",
    "options": {}
  },
  "transforms": [
    {
      "transform": "filter",
      "match": {
        "Bar": "row"
      },
      "drop": {
        "Baz": { "eq": 456 }
      }
    },
    {
      "transform": "mutate",
      "override": {
        "Fie": "where's my fum?"
      },
      "map": {
        "Foo": "Foo",
        "Bar": "Bar",
        "Bazzy": "Bazzy"
      }
    }
  ]
}
