### json_foofile > es_foo_schema_pk
POST http://localhost:8089/node/transfer HTTP/1.1
Authorization: Basic user user
Content-Type: application/json

{
  "tract": {
    "origin": {
      "SMT": "json_foofile",
      "options": {}
    },
    "terminal": {
      "SMT": "es_foo_schema_pk",
      "options": {}
    }
  }
}

### csv_foofile => mysql_foo_schema_pk
POST http://localhost:8089/node/transfer HTTP/1.1
Authorization: Basic user user
Content-Type: application/json

{
  "origin": {
    "SMT": "csv_foofile",
    "options": {
      "csvHeader": true
    }
  },
  "terminal": {
    "SMT": "mysql_foo_schema_pk",
    "options": {}
  }
}

### mysql_foo_schema_pk => es_foo_transfer
POST http://localhost:8089/node/transfer HTTP/1.1
Authorization: Basic user user
Content-Type: application/json

{
  "origin": {
    "SMT": "mysql_foo_schema_pk",
    "options": {}
  },
  "terminal": {
    "SMT": "es_foo_transfer",
    "options": {}
  }
}

### es_foo_schema_pk => mysql_foo_transfer
POST http://localhost:8089/node/transfer HTTP/1.1
Authorization: Basic user user
Content-Type: application/json

{
  "origin": {
    "SMT": "es_foo_schema_pk",
    "options": {}
  },
  "terminal": {
    "SMT": "mysql_foo_transfer",
    "options": {}
  },
  "transforms": {
    "select": {
      "fields": {
        "Foo": "Foo",
        "Bar": "Bar",
        "Baz": "Baz",
        "Fobe": "Fobe",
        "Dt Test": "Dt Test",
        "enabled": "enabled"
      }
    }
  }
}

### rest_weather_forecast => es_weather_forecast
POST http://localhost:8089/node/transfer HTTP/1.1
Authorization: Basic user user
Content-Type: application/json

{
  "origin": {
    "SMT": "rest_weather_forecast",
    "options": {
        "headers": {
          "Accept": "application/ld+json",
          "User-Agent": "@dictadata.org/storage-node contact:info@dictadata.org"
        },
        "reader": {
          "extract": {
            "encoding": "",
            "data": "periods"
          }
        }
    }
  },
  "terminal": {
    "SMT": "es_weather_forecast",
    "options": {}
  }
}

### rest_weather_forecast => mssql_weather_forecast
POST http://localhost:8089/node/transfer HTTP/1.1
Authorization: Basic user user
Content-Type: application/json

{
  "origin": {
    "SMT": "rest_weather_forecast",
    "options": {
        "headers": {
          "Accept": "application/ld+json",
          "User-Agent": "@dictadata.org/storage-node contact:info@dictadata.org"
        },
        "reader": {
          "extract": {
            "encoding": "",
            "data": "periods"
          }
        }
    }
  },
  "terminal": {
    "SMT": "mssql_weather_forecast",
    "options": {}
  }
}

### rest_weather_forecast => mysql_weather_forecast
POST http://localhost:8089/node/transfer HTTP/1.1
Authorization: Basic user user
Content-Type: application/json

{
  "origin": {
    "SMT": "rest_weather_forecast",
    "options": {
        "headers": {
          "Accept": "application/ld+json",
          "User-Agent": "@dictadata.org/storage-node contact:info@dictadata.org"
        },
        "reader": {
          "extract": {
            "encoding": "",
            "data": "periods"
          }
        }
    }
  },
  "terminal": {
    "SMT": "mysql_weather_forecast",
    "options": {}
  }
}


### rest_weather_forecast => oracle_weather_forecast
POST http://localhost:8089/node/transfer HTTP/1.1
Authorization: Basic user user
Content-Type: application/json

{
  "origin": {
    "SMT": "rest_weather_forecast",
    "options": {
        "headers": {
          "Accept": "application/ld+json",
          "User-Agent": "@dictadata.org/storage-node contact:info@dictadata.org"
        },
        "reader": {
          "extract": {
            "encoding": "",
            "data": "periods"
          }
        }
    }
  },
  "terminal": {
    "SMT": "oracle_weather_forecast",
    "options": {}
  }
}
