### elasticsearch junction.smt.schema
POST http://localhost:8089/node/list/es_foo_schema_pk HTTP/1.1
Authorization: Basic admin admin

### elasticsearch *
POST http://localhost:8089/node/list/es_foo_schema_pk?schema=* HTTP/1.1
Authorization: Basic admin admin

### elasticsearch foo*
POST http://localhost:8089/node/list HTTP/1.1
Authorization: Basic admin admin
Content-Type: application/json

{
  "SMT": "es_foo_schema_pk",
  "schema": "foo*"
}


### mssql junction.smt.schema
POST http://localhost:8089/node/list/mssql_foo_schema_pk HTTP/1.1
Authorization: Basic admin admin

### mssql *
POST http://localhost:8089/node/list/mssql_foo_schema_pk?schema=* HTTP/1.1
Authorization: Basic admin admin

### mssql foo*
POST http://localhost:8089/node/list HTTP/1.1
Authorization: Basic admin admin
Content-Type: application/json

{
  "SMT": "mssql_foo_schema_pk",
  "schema": "foo*"
}


### mysql junction.smt.schema
POST http://localhost:8089/node/list/mysql_foo_schema_pk HTTP/1.1
Authorization: Basic admin admin

### mysql *
POST http://localhost:8089/node/list/mysql_foo_schema_pk?schema=* HTTP/1.1
Authorization: Basic admin admin

### mysql foo*
POST http://localhost:8089/node/list HTTP/1.1
Authorization: Basic admin admin
Content-Type: application/json

{
  "SMT": "mysql_foo_schema_pk",
  "schema": "foo*"
}
