### transfer with transforms
POST http://localhost:8089/node/transfer HTTP/1.1
Authorization: Basic user user
Content-Type: application/json

{
  "source": {
    "SMT": "mysql_foo_schema_pk",
    "options": {}
  },
  "destination": {
    "SMT": "es_foo_transfer_3",
    "options": {}
  },
  "transforms": {
    "filter": {
      "match": {
        "Bar": "row"
      },
      "drop": {
        "Baz": { "eq": 456 }
      }
    },
    "fields": {
      "inject_before": {
        "Fie": "where's es fum?"
      },
      "mapping": {
        "Foo": "Foo",
        "Bar": "Bar",
        "Baz": "Bazzy"
      }
    }
  }
}

### transfer with transforms
POST http://localhost:8089/node/transfer HTTP/1.1
Authorization: Basic user user
Content-Type: application/json

{
  "source": {
    "SMT": "es_foo_transfer_3",
    "options": {}
  },
  "destination": {
    "SMT": "mysql_foo_transfer_3",
    "options": {}
  },
  "transforms": {
    "filter": {
      "match": {
        "Bar": "row"
      },
      "drop": {
        "Baz": { "eq": 456 }
      }
    },
    "fields": {
      "inject_after": {
        "Fie": "where's my fum?"
      },
      "mapping": {
        "Foo": "Foo",
        "Bar": "Bar",
        "Bazzy": "Bazzy"
      }
    }
  }
}
