### elasticsearch|http://localhost:9200|foo_schema|first
GET http://localhost:8089/node/recall/es_foo_schema_id HTTP/1.1
Authorization: Basic admin admin

### elasticsearch|http://localhost:9200|foo_schema|!
GET http://localhost:8089/node/recall/es_foo_schema_ks HTTP/1.1
Authorization: Basic admin admin
Content-Type: application/json

{
  "key": "twenty"
}

### elasticsearch|http://localhost:9200|foo_schema|!Foo
GET http://localhost:8089/node/recall/es_foo_schema_kf HTTP/1.1
Authorization: Basic admin admin
Content-Type: application/json

{
  "Foo": "ten"
}

### elasticsearch|http://localhost:9200|foo_schema|=Foo
GET http://localhost:8089/node/recall HTTP/1.1
Authorization: Basic admin admin
Content-Type: application/json

{
  "SMT": "es_foo_schema_pk",
  "pattern": {
    "match": {
      "Foo": "twenty"
    }
  }
}

### mysql|host=localhost;user=dicta;password=dicta;database=storage_node|foo_schema|=Foo
GET http://localhost:8089/node/recall/mysql_foo_schema_pk HTTP/1.1
Authorization: Basic admin admin
Content-Type: application/json

{
  "pattern": {
    "match": {
      "Foo": "twenty"
    }
  }
}
