### transfer foofile.json > elasticsearch
POST http://localhost:8089/node/transfer HTTP/1.1
Authorization: Basic user user
Content-Type: application/json

{
  "tract": {
    "origin": {
      "SMT": "json_foofile",
      "options": {}
    },
    "terminal": {
      "SMT": "es_foo_schema_pk",
      "options": {}
    }
  }
}

### transfer foofile.csv > mysql
POST http://localhost:8089/node/transfer HTTP/1.1
Authorization: Basic user user
Content-Type: application/json

{
  "origin": {
    "SMT": "csv_foofile",
    "options": {
      "csvHeader": true
    }
  },
  "terminal": {
    "SMT": "mysql_foo_schema_pk",
    "options": {}
  }
}

### transfer mysql > elasticsearch
POST http://localhost:8089/node/transfer HTTP/1.1
Authorization: Basic user user
Content-Type: application/json

{
  "origin": {
    "SMT": "mysql_foo_schema_pk",
    "options": {}
  },
  "terminal": {
    "SMT": "es_foo_transfer",
    "options": {}
  }
}

### transfer elasticsearch > mysql
POST http://localhost:8089/node/transfer HTTP/1.1
Authorization: Basic user user
Content-Type: application/json

{
  "origin": {
    "SMT": "es_foo_schema_pk",
    "options": {}
  },
  "terminal": {
    "SMT": "mysql_foo_transfer",
    "options": {}
  },
  "transforms": {
    "select": {
      "fields": {
        "Foo": "Foo",
        "Bar": "Bar",
        "Baz": "Baz",
        "Fobe": "Fobe",
        "Dt Test": "Dt Test",
        "enabled": "enabled"
      }
    }
  }
}

### REST weather > elasticsearch
POST http://localhost:8089/node/transfer HTTP/1.1
Authorization: Basic user user
Content-Type: application/json

{
  "origin": {
    "SMT": "rest_weather_forecast",
    "options": {
        "headers": {
          "Accept": "application/ld+json",
          "User-Agent": "@dictadata.org/storage-node contact:info@dictadata.org"
        },
        "reader": {
          "extract": {
            "encoding": "",
            "data": "periods"
          }
        }
    }
  },
  "terminal": {
    "SMT": "es_weather_forecast",
    "options": {}
  }
}

### REST weather > mssql
POST http://localhost:8089/node/transfer HTTP/1.1
Authorization: Basic user user
Content-Type: application/json

{
  "origin": {
    "SMT": "rest_weather_forecast",
    "options": {
        "headers": {
          "Accept": "application/ld+json",
          "User-Agent": "@dictadata.org/storage-node contact:info@dictadata.org"
        },
        "reader": {
          "extract": {
            "encoding": "",
            "data": "periods"
          }
        }
    }
  },
  "terminal": {
    "SMT": "mssql_weather_forecast",
    "options": {}
  }
}

### REST weather > mysql
POST http://localhost:8089/node/transfer HTTP/1.1
Authorization: Basic user user
Content-Type: application/json

{
  "origin": {
    "SMT": "rest_weather_forecast",
    "options": {
        "headers": {
          "Accept": "application/ld+json",
          "User-Agent": "@dictadata.org/storage-node contact:info@dictadata.org"
        },
        "reader": {
          "extract": {
            "encoding": "",
            "data": "periods"
          }
        }
    }
  },
  "terminal": {
    "SMT": "mysql_weather_forecast",
    "options": {}
  }
}

