### transfer test
GET http://localhost:8089/node/transfer/test HTTP/1.1
Authorization: Basic admin admin

### transfer
POST http://localhost:8089/node/transfer HTTP/1.1
Authorization: Basic user user
Content-Type: application/json

{
  "source": {
    "SMT": "csv_foofile",
    "options": {}
  },
  "destination": {
    "SMT": "mysql_foo_schema_pk",
    "options": {}
  }
}

### transfer
POST http://localhost:8089/node/transfer HTTP/1.1
Authorization: Basic user user
Content-Type: application/json

{
  "source": {
    "SMT": "mysql_foo_schema_pk",
    "options": {}
  },
  "destination": {
    "SMT": "es_foo_transfer_2",
    "options": {}
  }
}

### weather
POST http://localhost:8089/node/transfer HTTP/1.1
Authorization: Basic user user
Content-Type: application/json

{
  "source": {
    "SMT": "rest_weather_forecast",
    "options": {
        "headers": {
          "Accept": "application/ld+json",
          "User-Agent": "@dictadata.org/storage-node contact:info@dictadata.org"
        },
        "reader": {
          "extract": {
            "encoding": "",
            "data": "periods"
          }
        }
    }
  },
  "destination": {
    "SMT": "mysql_rest_forecast",
    "options": {}
  }
}

