/**
 * account.js
 */
"use strict";

const roles = require('./roles');
const crypto = require("crypto");

module.exports = class Account {

  /**
   * account constructor
   * @param {*} userid
   */
  constructor (userid = '') {
    this.userid = userid;
    this.password = '';
    this.roles = [roles.Public];
    this.dateCreated = null;
    this.dateUpdated = null;
    this.lastLogin = null;

    // state can be copied, but shouldn't be saved, updated or communicated
    this.state = {
      isAuthenticated: false
    };

    this.profile = {
      provider: '', // The provider with which the account authenticated (facebook, twitter, etc.).
      id: '', // A unique identifier for the account, as generated by the service provider.
      displayName: '', // The name of this account, suitable for display.
      name: {
        familyName: '', // The family name of this user, or "last name" in most Western languages.
        givenName: '', // The given name of this user, or "first name" in most Western languages.
        middleName: '' // The middle name of this user.
      },
      emails: [{
        value: '', // The actual email address.
        type: '' // The type of email address (home, work, etc.).
      }],
      photos: [{
        value: '' // The URL of the image.
      }]
    };

    this.settings = {
      prefix: '',
      homepage: ''
    };
  }

  /**
   * Hash plain text passwords.
   *
   * @param pwd The string to be hashed.
   * @returns {*} A string containing the hash results.
   */
  static hashPwd(pwd) {
    let hash = crypto.createHash("sha1");
    hash.update(pwd, "utf8");
    return hash.digest("base64");
  }

  get isAuthenticated () {
    return this.state.isAuthenticated;
  }
  set isAuthenticated (value) {
    this.state.isAuthenticated = value;
  }

  hasRole(role) {
    return this.roles.includes(role);
  }

  // shallow copy of all non-function properties
  copy(a2) {
    let a1 = this;

    Object.keys(a2).forEach( function(key) {
      let t = typeof a2[key];
      if (t !== "undefined" && t !== "function") {
        a1[key] = a2[key];
      }
    });
  }

  // shallow copy of all non-function properties
  // not including userid, password, roles, state
  merge(a2) {
    let a1 = this;

    Object.keys(a2).forEach( function(key) {
      let t = typeof a2[key];

      if (key !== 'userid' && key === 'password'
       && key === 'roles' && key === 'state'
       && t !== "undefined" && t !== "function")
      {
        a1[key] = a2[key];
      }
    });
  }

  /**
   * shallow copy of account for sharing
   * stripped of password, state and functions
   */
  package() {
    let a1 = {};
    let a2 = this;

    Object.keys(this).forEach( function(key) {
      let t = typeof a2[key];

      if (key === 'password') {
        //a1.password = a2.password;
      } else if (key === 'state') {
        //a1.state = a2.state;
      } else if (t !== "undefined" && t !== "function") {
        a1[key] = a2[key];
      }
    });

    return a1;
  }

};
