/**
 * user.js
 */
"use strict";

const roles = require('./roles');

module.exports = class User {

  /**
   * user constructor
   * @param {*} username
   */
  constructor (userid = '') {
    this.userid = userid;
    this.password = '';
    this.roles = [roles.Public];
    this.dateCreated = null;
    this.dateUpdated = null;
    this.lastLogin = null;

    // state can be copied, but shouldn't be saved, updated or communicated
    this.state = {
      isAuthenticated: false
    }

    this.profile = {
      provider: '', // The provider with which the user authenticated (facebook, twitter, etc.).
      id: '', // A unique identifier for the user, as generated by the service provider.
      displayName: '', // The name of this user, suitable for display.
      name: {
        familyName: '', // The family name of this user, or "last name" in most Western languages.
        givenName: '', // The given name of this user, or "first name" in most Western languages.
        middleName: '' // The middle name of this user.
      },
      emails: [{
        value: '', // The actual email address.
        type: '' // The type of email address (home, work, etc.).
      }],
      photos: [{
        value: '' // The URL of the image.
      }]
    };

    this.settings = {
      prefix: '',
      homepage: ''
    }
  }

  verifyPassword(password) {
    if (password && password === this.password) {
      this.state.isAuthenticated = true;
    } else {
      this.state.isAuthenticated = false;
    }
    return this.state.isAuthenticated;
  }

  copy(u2) {
    let u1 = this;

    Object.keys(u2).forEach( function(key) {
      let t = typeof u2[key];

      if (key === 'roles') {
        u1.roles = u2.roles;
      } else if (key === 'state') {
        u1.state = u2.state;
      } else if (key === 'profile') {
        u1.profile = u2.profile;
      } else if (key === 'settings') {
        u1.settings = u2.settings;
      } else if (t !== "undefined" && t !== "function") {
        u1[key] = u2[key];
      }
    });
  }

  update(u2) {
    let u1 = this;

    Object.keys(u2).forEach( function(key) {
      let t = typeof u2[key];

      if (key === 'roles') {
        u1.roles = u2.roles;
      } else if (key === 'state') {
        //u1.state = u2.state;
      } else if (key === 'profile') {
        u1.profile = u2.profile;
      } else if (key === 'settings') {
        u1.merge(u1.settings, u2.settings);
      } else if (t !== "undefined" && t !== "function") {
        u1[key] = u2[key];
      }
    });
  }

  /**
   * return object for saving or communicating
   * strip fields and functions
   */
  package() {
    let u1 = {};
    let u2 = this;

    Object.keys(this).forEach( function(key) {
      let t = typeof u2[key];

      if (key === 'password') {
        //u1.password = u2.password;
      } else if (key === 'state') {
        //u1.state = u2.state;
      } else if (key === 'profile') {
        u1.profile = u2.profile
      } else if (key === 'settings') {
        u1.settings = u2.settings;
      } else if (t !== "undefined" && t !== "function") {
        u1[key] = u2[key];
      }
    });

    return u2;
  }

  merge(u1,u2) {
    Object.keys(u2).forEach( function(key) {
      let t = typeof u2[key];
      if (t !== "undefined" && t !== "function") {
        u1[key] = u2[key];
      }
    });
  }

};
