### Install Visual Studio Code extension: REST Client  humao.rest-client

### guest doesn't normally have User rights
PUT http://localhost:8089/node/account HTTP/1.1
Authorization: Basic guest guest
Content-Type: application/json

{
    "userid": "guest",
    "password": "guest",
    "roles": ["Public","User"],
    "settings": {
      "homepage": "/guest/myhomepage",
      "theme": "light"
    }
}

### change guest by admin
PUT http://localhost:8089/node/account HTTP/1.1
Authorization: Basic admin admin
Content-Type: application/json

{
    "userid": "guest",
    "password": "guest",
    "roles": ["Public","User"],
    "settings": {
      "homepage": "/guest/myhomepage",
      "theme": "light"
    }
}

### change admin by admin
PUT http://localhost:8089/node/account HTTP/1.1
Authorization: Basic admin admin
Content-Type: application/json

{
    "userid": "admin",
    "password": "admin",
    "roles": ["Public","User","Admin","Monitor"],
    "settings": {
      "homepage": "/home",
      "theme": "dark"
    }
}
