### Install Visual Studio Code extension: REST Client  humao.rest-client

### no user
GET http://localhost:8089/node/login HTTP/1.1

### nobody@nowheresville.com:gonebaby
GET http://localhost:8089/node/login HTTP/1.1
Authorization: Basic nobody@nowheresville.com gonebaby

### guest:guest
GET http://localhost:8089/node/login HTTP/1.1
Authorization: Basic guest guest

### admin:admin  regular endpoint
GET http://localhost:8089/node/account HTTP/1.1
Authorization: Basic admin admin
