### Install Visual Studio Code extension: REST Client  humao.rest-client

### guest:guest - guest does not have User rights
PUT http://localhost:8089/node/account HTTP/1.1
Authorization: Basic guest guest
Content-Type: application/json

{
    "userid": "guest",
    "password": "guest",
    "roles": ["Public","User"],
    "settings": {
      "homepage": "/guest/myhomepage",
      "theme": "light"
    }
}

### guest:guest - changed by admin
PUT http://localhost:8089/node/account HTTP/1.1
Authorization: Basic admin admin
Content-Type: application/json

{
    "userid": "guest",
    "password": "guest",
    "roles": ["Public","User"],
    "settings": {
      "homepage": "/guest/myhomepage",
      "theme": "dark"
    }
}

### user:user, will not get Admin rights
PUT http://localhost:8089/node/account HTTP/1.1
Authorization: Basic user user
Content-Type: application/json

{
    "userid": "user",
    "password": "user",
    "roles": ["Public","User","Admin"],
    "settings": {
      "homepage": "/home",
      "theme": "green"
    }
}
