### no user: unauthorized
GET http://localhost:8089/status HTTP/1.1

### invalid Authorization: defaults to Public roles
GET http://localhost:8089/status HTTP/1.1
Authorization: Basic Aladdin opensesame

### Public guest:guest
GET http://localhost:8089/status HTTP/1.1
Authorization: Basic guest guest

### User admin:admin
GET http://localhost:8089/status HTTP/1.1
Authorization: Basic admin admin
