### drew@drewletcher.net
POST http://localhost:8089/node/retrieve/elastic|*|hupp_equipment_repair_history|* HTTP/1.1
Authorization: Basic ZHJld0BkcmV3bGV0Y2hlci5uZXQ6cGl6emEx
Content-Type: application/json

{
  "pattern": {
    "filter": {
      "dealer": "City ForkLift",
      "invoice_date": { "gte": "2016-01-01", "lte": "2016-12-31" }
    },
    "cues": {
      "count": 10,
      "order": {"asset_num": "asc"}
    }
  }
}

### mysql|host=localhost;user=dicta;password=dicta;database=storage_node|test_table|=Foo
POST http://localhost:8089/node/retrieve/mysql%7Chost%3Dlocalhost%3Buser%3Ddicta%3Bpassword%3Ddicta%3Bdatabase%3Dstorage_node%7Ctest_schema%7C%3DFoo HTTP/1.1
Authorization: Basic user user
Content-Type: application/json

{
  "filter": {
    "Foo": "first"
  }
}

### mysql|host=localhost;user=dicta;password=dicta;database=storage_node|test_table|=Foo
POST http://localhost:8089/node/retrieve/mysql%7Chost%3Dlocalhost%3Buser%3Ddicta%3Bpassword%3Ddicta%3Bdatabase%3Dstorage_node%7Ctest_schema%7C%3DFoo HTTP/1.1
Authorization: Basic user user
Content-Type: application/json

{
  "pattern": {
    "filter": {
      "Foo": "first"
    }
  }
}
